### ISSUE TITLE
shortcode use markup from lite

### ISSUE THREAD

**Issue by selul** [Codeinwp/wppr-single-review-shortcode#10]
@contactashish13 we have 3 values for visual attr and only the full one is using the markup from the lite version. 

What i would like to do is for the other 2 values aswell to use the cwppos_show_review which will receive a 2nd param, the view mode, by default set to full. 

based on the arg value you display the proper markup for the according selection. 

here you have details about the view for each param value: 

http://prntscr.com/c8zc21

**Comment by selul** [comment]
@contactashish13 you just moved the function from addon to the lite did the same thing :D 
 
please rename this function back https://github.com/Codeinwp/wp-product-review/blob/development/inc/wppr-main.php#L111 

to cwppos_show_review 

and based on the $visual value show the proper markup 

For instance when yes is showed, the $return_string   variable will contain the markup code from the full review that show the circle 

The same thing for no value.

Let me know if you have any questions

**Comment by contactashish13** [comment]
@selul I created a new function **cwppos_show_review_full** which is called from **cwppos_show_review** when the value for visual is full. When the value is not full, it uses the same logic as before but inside **cwppos_show_review** function.

**Comment by selul** [comment]
yes, but i dont want this i want a single function but remove html tags based on the visual value for the return string.

**Comment by contactashish13** [comment]
@selul sorry, I don't understand

**Comment by selul** [comment]
ok, the full layout of the review is shown when the $visual = full, which is the current return value of the **cwppos_show_review** / **cwppos_show_review_full** function.

We have 2 more values for the visual, yes or no. The yes will show the green circle with the rating value, the no will show the rating value. Both of them are included in the full review code. 

Let's say we have this markup code for the full review  and let's imagine the return string will look like this: 

```
$return_string .= " < div class="review" > <h1 > Title Review </h1> ";
$return_string .= " <div  class="score_circle> ";
$return_string .= " 81  ";
$return_string .= " </div> ";
$return_string .= " </div>";
```

Following my logic of using the visual value to alter the return string we will refactor to this: 
```
$return_string  = ""; 
if ( $visual == " full ") { 
   $return_string .= " < div class="review" > <h1 > Title Review </h1> ";
} 
if ( $visual == " yes") { 
   $return_string .= " <div  class="score_circle>  ";
} 

$return_string .= " 81  ";

if ( $visual == " yes") { 
   $return_string .= " </div>  ";
} 

if ( $visual == " full ") { 
   $return_string .= " </div>  ";
} 
```
Do you have things clear now ?

**Comment by contactashish13** [comment]
@selul thanks for clarifying :) Have pushed in the changes.
