### ISSUE TITLE
Render Blocking Script

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wppr-single-review-shortcode#3]
Source: https://themeisle.com/forums/topic/render-blocking-script/

I really enjoy your plugin, but I have found a few issues with your code. Here is what I have found.
1. you are loading javascript and css for this plugin when my page doesn’t have any reviews
2. you are adding render blocking script into the header which google complains about.
3. you are adding inline css to my page.
4. you appear to be loading java script in the head instead of the bottom of the page.

Are you aware of these issues?

@ineagu

**Comment by ineagu** [comment]
@HardeepAsrani yes, we are aware, we are working on different optimizations.

@selu91
