### ISSUE TITLE
Shortcodes display review at the beginning of the post

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/wppr-single-review-shortcode#5]
Shortcodes like "[P_REVIEW post_id=3067 visual='full']" will display the review at the beginning of the post instead of where it's placed.

@ineagu

**Comment by ineagu** [comment]
examples ? poate sa fie o problema de float ceva .

**Comment by mariusghitulescu** [comment]
@ineagu nu vazusem notificarea. Face asa pe orice tema incercata, nu e doar float. Shortcode-ul va aparea intotdeauna la inceputul postarii.

**Comment by ineagu** [comment]
si la noi de dev2 de ce arata ok ? :D

**Comment by mariusghitulescu** [comment]
A fost rezolvat intre timp? Am verificat acum pe acelasi site pe care am verificat si inainte cand a fost raportata problema, acum merge intotdeauna. Dubios :)
